services:
  - type: web
    name: blogdojo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Use gunicorn for production
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: blogdojo-postgres
          property: connectionString
